[project]
name = "flights"
version = "0.0.1"
authors = [{"name" = "LR"}]
description = "Simplistic package"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"flights" = "./flights"}